import ReduxProvider from "@/redux/ReduxProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
		<html lang="en">
			<meta name="application-name" content="E-Office" />
			<meta name="apple-mobile-web-app-capable" content="yes" />
			<meta name="apple-mobile-web-app-status-bar-style" content="default" />
			<meta name="apple-mobile-web-app-title" content="E-Office" />
			<meta name="format-detection" content="telephone=no" />
			<meta name="mobile-web-app-capable" content="yes" />
			<meta name="msapplication-TileColor" content="#2B5797" />
			<meta name="msapplication-tap-highlight" content="no" />
			<meta name="theme-color" content="#000000" />

			<link rel="apple-touch-icon" href="/ios/128.png" />
			<link rel="apple-touch-icon" sizes="152x152" href="/ios/152.png" />
			<link rel="apple-touch-icon" sizes="180x180" href="/ios/180.png" />
			<link rel="apple-touch-icon" sizes="167x167" href="/ios/167.png" />
			<link rel="icon" type="image/png" sizes="32x32" href="/ios/32.png" />
			<link rel="icon" type="image/png" sizes="16x16" href="/ios/16.png" />
			<link rel="manifest" href="/manifest.json" />
			<body className={`${inter.className} ${inter.variable} font-sans`}>
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	);
}
